#%RAML 1.0 SecurityScheme
type: x-token-authorize
description: This will make sure that we have Authtorization header
describedBy:
  headers:
    client_id:
      type: string
    client_secret:
      type: string
  responses:
    "401":
      description: 401-Unauthorized